[package]
name = "pronto"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
prettytable-rs = "^0.8"
console = "0.15.0"
chrono = "0.4"
structopt = "0.3.22"